#!/bin/bash

file=../assemble_summaries/summary_counts.xls
genome="Methylotenera mobilis JLW8"

# this needs to be a for loop over the genome names that substitutes them in for $genome
R --no-save --args $file "$genome" < normalize.R
