#!/bin/bash

#PBS -N "LakWasMe99_LOW12_2_aln"
#PBS -d /gscratch/lidstrom/meta4/workspace/LakWasMe99_LOW12_2/bwa
#PBS -l walltime=999:99:99,mem=2gb,feature=8core,nodes=1:ppn=8
#PBS -W umask=002
#PBS -W group_list=hyak-lidstrom
#PBS -M dacb@uw.edu,jmatsen@uw.edu
#PBS -m abe
#PBS -o aln.log
#PBS -e aln.err

/gscratch/lidstrom/software/bwa/bin/bwa mem -p -M -t 8 /gscratch/lidstrom/meta4/data/isolate_genomes.fasta /gscratch/lidstrom/meta4/data/LakWasMe99_LOW12_2/Raw_Data/8903.5.115182.ATACGG.fastq.gz > LakWasMe99_LOW12_2.sam
