#!/bin/bash

#PBS -N "LakWasMet55_HOW8_2_aln"
#PBS -d /gscratch/lidstrom/meta4/workspace/LakWasMet55_HOW8_2/bwa
#PBS -l walltime=999:99:99,mem=2gb,feature=8core,nodes=1:ppn=8
#PBS -W umask=002, group_list=hyak-lidstrom
#PBS -M dacb@uw.edu,jmatsen@uw.edu
#PBS -m abe
#PBS -o aln_make_sam.log
#PBS -e aln_make_sam.err

# note: output name is LakWasMet55_HOW8_2_new.sam, which will not get deleted by the database command (LakWasMet55_HOW8_2.sam does)
/gscratch/lidstrom/software/bwa/bin/bwa mem -M -t 8 /gscratch/lidstrom/meta4/data/isolate_genomes.fasta /gscratch/lidstrom/meta4/data/LakWasMet55_HOW8_2/Raw_Data/r1.fastq.gz /gscratch/lidstrom/meta4/data/LakWasMet55_HOW8_2/Raw_Data/r2.fastq.gz > LakWasMet55_HOW8_2_new.sam
