#!/bin/bash

#PBS -N "LakWasMet55_HOW8_2_aln"
#PBS -d /gscratch/lidstrom/meta4/workspace/LakWasMet55_HOW8_2/bwa
#PBS -l walltime=999:99:99,mem=2gb,feature=8core,nodes=1:ppn=8
#PBS -W umask=002, group_list=hyak-lidstrom
#PBS -M dacb@uw.edu,jmatsen@uw.edu
#PBS -m abe
#PBS -o bam_to_sam.log
#PBS -e bam_to_sam.err

# https://www.biostars.org/p/1701/
	# $ samtools view -h -o out.sam in.bam
	# the h is important: header
samtools view  -h -o  LakWasMet55_HOW8_2.sorted.sam LakWasMet55_HOW8_2.sorted.bam


