#!/bin/bash

#PBS -N "LakWasMet55_HOW8_2_samtools"
#PBS -d /gscratch/lidstrom/meta4/workspace/LakWasMet55_HOW8_2/bwa
#PBS -l walltime=999:99:99,mem=2gb,feature=8core,nodes=1:ppn=8
#PBS -W umask=002, group_list=hyak-lidstrom
#PBS -M dacb@uw.edu,jmatsen@uw.edu
#PBS -m abe
#PBS -o samtools.log
#PBS -e samtools.err

# convert the sam to bam
/gscratch/lidstrom/software/samtools/bin/samtools view -bt /gscratch/lidstrom/meta4/data/isolate_genomes.fasta -o LakWasMet55_HOW8_2.bam LakWasMet55_HOW8_2.sam
# sort according to bases in the scaffold.  
/gscratch/lidstrom/software/samtools/bin/samtools sort LakWasMet55_HOW8_2.bam LakWasMet55_HOW8_2.sorted
# index the bam
/gscratch/lidstrom/software/samtools/bin/samtools index LakWasMet55_HOW8_2.sorted.bam
# apply htseq-count to get counts per feature (feature = gene? base?).   
/gscratch/lidstrom/software/htseq/bin/htseq-count -m intersection-nonempty -s no -t gene -i ID LakWasMet55_HOW8_2.sam /gscratch/lidstrom/meta4/data/isolate_genomes.gbk.gff > LakWasMet55_HOW8_2.summary.dat
# \rm temporarily disables alias.  In this case it prevents you from asking "are you sure you want to delete it?" in interactive mode. 
\rm -r LakWasMet55_HOW8_2.bam
