#!/bin/bash

awk '{ if (substr($1, 1, 1) == ">") if ($1 == ">2516143013") printf(">m77_scaffold1\t%s\n", $0); else if ($1 == ">2516143873") printf(">m11_scaffold1\t%s\n", $0); else if ($1 == ">2516143971") printf(">m5_scaffold1\t%s\n", $0); else printf(">%s\t%s\n", $2, $0); else if (NF > 0) print $0; }' isolate_genomes.original.fasta
