#!/bin/bash

#PBS -N "LakWasMeta2_LOW4_2_samtools"
#PBS -d /gscratch/lidstrom/meta4/workspace/LakWasMeta2_LOW4_2/bwa
#PBS -l walltime=999:99:99,mem=2gb,feature=8core,nodes=1:ppn=8
#PBS -W umask=002
#PBS -W group_list=hyak-lidstrom
#PBS -M dacb@uw.edu,jmatsen@uw.edu
#PBS -m abe
#PBS -o samtools.log
#PBS -e samtools.err

/gscratch/lidstrom/software/samtools/bin/samtools view -bt /gscratch/lidstrom/meta4/data/isolate_genomes.fasta -o LakWasMeta2_LOW4_2.bam LakWasMeta2_LOW4_2.sam
/gscratch/lidstrom/software/samtools/bin/samtools sort LakWasMeta2_LOW4_2.bam LakWasMeta2_LOW4_2.sorted
/gscratch/lidstrom/software/samtools/bin/samtools index LakWasMeta2_LOW4_2.sorted.bam
/gscratch/lidstrom/software/htseq/bin/htseq-count -m intersection-nonempty -s no -t gene -i ID LakWasMeta2_LOW4_2.sam /gscratch/lidstrom/meta4/data/isolate_genomes.gbk.gff > LakWasMeta2_LOW4_2.summary.dat
\rm -r LakWasMeta2_LOW4_2.bam
