#!/bin/bash

source globals.sh

SQL=extract_counts.sql
\rm -rf $SQL

if [ $# -lt 1 ]
then
        where=""
elif [ $# -eq 1 ]
then
        where="WHERE type = '$1'"
else
        echo "usage: $0 <type, e.g. CDS, tRNA, rRNA>"
        exit 1
fi

#conditions=`echo "SELECT DISTINCT(shortd) FROM sample_info WHERE include = 1 AND is_qc = 0 ORDER BY shortd;" | mysql -h $HOST $DB -s`
conditions=`echo "SELECT DISTINCT(shortd) FROM sample_info WHERE include = 1 ORDER BY shortd;" | mysql -h $HOST $DB -s`

#printf "SELECT g.locus_tag, g.product" >> $SQL
printf "SELECT g.locus_tag" >> $SQL
for condition in $conditions
do
        samples=`echo "SELECT sample FROM sample_info WHERE shortd = '$condition' ORDER BY sample;" | mysql -h $HOST $DB -s`
        for sample in $samples
        do
                printf ", ROUND($sample.reads_mapped) AS $sample" >> $SQL
        done
done
cat << EOF >> $SQL
	FROM (
		SELECT locus_tag, type FROM genes_31_32_FL_13
			UNION
		SELECT locus_tag, type FROM genes_31_32_FL_JLW8
	) AS g
EOF
for condition in $conditions
do
        samples=`echo "SELECT sample FROM sample_info WHERE shortd = '$condition' ORDER BY sample;" | mysql -h $HOST $DB -s`
        for sample in $samples
        do
                printf "\t\tLEFT JOIN summary_${sample} AS $sample ON $sample.locus_tag = g.locus_tag\n" >> $SQL
        done
done
printf "\t$where\n;" >> $SQL

mysql -h $HOST $DB < $SQL | sed "s/NULL/0/g"

