#!/bin/bash

source globals.sh

HERE=`pwd`

mysql -h $HOST $DB << EOF
LOAD DATA INFILE "$HERE/sample_info.xls" INTO TABLE sample_info FIELDS TERMINATED BY '\t' IGNORE 1 LINES;
EOF

echo "SELECT * FROM sample_info;" | mysql -h $HOST $DB

samples=`echo "SELECT sample FROM sample_info;" | mysql -s -h $HOST $DB`
workspace_dir="`pwd | awk -F'/' '{ for (i=1; i < NF; ++i) printf("%s/", $i); printf("\n"); }'`workspace"

for sample in $samples
do
	dir=$workspace_dir/$sample
	echo "UPDATE sample_info SET path_to_workspace='$dir' WHERE sample='$sample';" | mysql -s -h $HOST $DB
	if [ -d $dir ]
	then
		echo skipping setup of $sample
		continue
	fi
	echo importing $sample 
	echo "making and populating $dir"
	mkdir -p $dir
	cd $dir

	fastq_R1=`echo "SELECT path_to_FASTQ_R1 FROM sample_info WHERE sample='$sample';" | mysql -s -h $HOST $DB`
	fastq_R2=`echo "SELECT path_to_FASTQ_R2 FROM sample_info WHERE sample='$sample';" | mysql -s -h $HOST $DB`
	genome_fasta=`echo "SELECT path_to_genome_FASTA FROM sample_info WHERE sample='$sample';" | mysql -s -h $HOST $DB`
	proteome_fasta=`echo "SELECT path_to_proteome_FASTA FROM sample_info WHERE sample='$sample';" | mysql -s -h $HOST $DB`
	gff=`echo "SELECT path_to_GFF FROM sample_info WHERE sample='$sample';" | mysql -s -h $HOST $DB`

	ln -sf $fastq_R1 .
	ln -sf $fastq_R2 .
	ln -sf $genome_fasta .
	ln -sf $proteome_fasta .
	ln -sf $gff .

	cd $HERE

	./sample_setup $sample
#	./sample_submit $sample
done
